# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUZi327f7DeBTy6iBgbb0QryWXoIuspS

#Phase A: Data Preprocessing
"""

# --- Step 1: Load and inspect the data ---
from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer()

# Turn it into a DataFrame so it's easy to look at
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target   # 0 = malignant, 1 = benign

print(df.shape)        # (rows, columns)
print(df['target'].value_counts())   # how many of each class
df.head()

# --- Step 2: Check for missing values ---
print(df.isnull().sum().sum())  # total count of missing values across the whole dataset

# --- Step 3: Train/test split ---
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)   # features (the 30 measurements)
y = df['target']                # labels (0 or 1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)

# --- Step 4: Feature scaling ---
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""#Phase B: Model Implementation

"""

# --- Step 5: Logistic Regression ---
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train_scaled, y_train)

y_pred_lr = lr_model.predict(X_test_scaled)

# --- Step 6: Random Forest ---
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)   # note: uses UNscaled data

y_pred_rf = rf_model.predict(X_test)

# --- Step 7: SVM ---
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_scaled, y_train)   # note: uses SCALED data again

y_pred_svm = svm_model.predict(X_test_scaled)

"""#Phase C: Evaluation - Collect metrics"""

# --- Step 8: Evaluation metrics ---
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred, model_name):
    return {
        'Model': model_name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred),
        'F1-score': f1_score(y_true, y_pred)
    }

results = [
    get_metrics(y_test, y_pred_lr, 'Logistic Regression'),
    get_metrics(y_test, y_pred_rf, 'Random Forest'),
    get_metrics(y_test, y_pred_svm, 'SVM'),
]

results_df = pd.DataFrame(results)
print(results_df)

"""##Confusion matrices"""

# --- Step 9: Confusion matrices ---
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
import os

os.makedirs('results', exist_ok=True)   # creates the folder if it doesn't exist

models_preds = {
    'Logistic_Regression': y_pred_lr,
    'Random_Forest': y_pred_rf,
    'SVM': y_pred_svm
}

for name, preds in models_preds.items():
    disp = ConfusionMatrixDisplay.from_predictions(y_test, preds, display_labels=['Malignant', 'Benign'])
    disp.ax_.set_title(f'Confusion Matrix - {name}')
    plt.savefig(f'results/confusion_matrix_{name}.png')
    plt.close()

"""##Comparison Chart"""

# --- Step 11: Specificity + full comparison chart ---
from sklearn.metrics import confusion_matrix

def get_specificity(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn + fp)   # true negative rate

def get_metrics(y_true, y_pred, model_name):
    return {
        'Model': model_name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred),
        'F1-score': f1_score(y_true, y_pred),
        'Specificity': get_specificity(y_true, y_pred)
    }

results = [
    get_metrics(y_test, y_pred_lr, 'Logistic Regression'),
    get_metrics(y_test, y_pred_rf, 'Random Forest'),
    get_metrics(y_test, y_pred_svm, 'SVM'),
]

results_df = pd.DataFrame(results)
print(results_df)

# --- Bar chart with all 5 metrics ---
results_df.set_index('Model')[['Accuracy', 'Precision', 'Recall', 'F1-score', 'Specificity']].plot(
    kind='bar', figsize=(10, 6)
)
plt.title('Disease Prediction Model Performance')
plt.xlabel('Machine Learning Model')
plt.ylabel('Score')
plt.ylim(0, 1.05)
plt.xticks(rotation=0)
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('results/model_comparison.png')
plt.close()

"""##ROC Curve"""

# --- Step 12: ROC Curve ---
from sklearn.metrics import roc_curve, roc_auc_score

# Get predicted PROBABILITIES (not just 0/1 labels) for the positive class (benign = 1)
y_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
y_prob_svm = svm_model.decision_function(X_test_scaled)  # SVM has no predict_proba by default

plt.figure(figsize=(8, 6))

for name, y_prob in [('Logistic Regression', y_prob_lr),
                      ('Random Forest', y_prob_rf),
                      ('SVM', y_prob_svm)]:
    fpr, tpr, thresholds = roc_curve(y_test, y_prob)
    auc = roc_auc_score(y_test, y_prob)
    plt.plot(fpr, tpr, label=f'{name} (AUC = {auc:.3f})')

plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('results/roc_curve.png')
plt.close()

"""###Cross-validation check"""

# --- Cross-validation check ---
from sklearn.model_selection import cross_val_score

for name, model in [('Logistic Regression', lr_model), ('Random Forest', rf_model), ('SVM', svm_model)]:
    scores = cross_val_score(model, scaler.fit_transform(X), y, cv=5)
    print(f'{name}: {scores.mean():.4f} (+/- {scores.std():.4f})')